package com.tp1.habittracker.domain.model;

public enum GraphEventType {
    USER_CREATED,
    USER_DELETED,
    HABIT_CREATED,
    HABIT_UPDATED,
    HABIT_DELETED,
    FRIENDSHIP_REQUEST_CREATED,
    FRIENDSHIP_REQUEST_ACCEPTED,
    FRIENDSHIP_REQUEST_DECLINED,
    FRIENDSHIP_REQUEST_CANCELLED,
    FRIENDSHIP_REMOVED
}
